<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'SeqArtMix\Module'                           => __DIR__ . '/SeqArtMix/Module.php',
  'SeqArtMix\Entity\Img'                       => __DIR__ . '/SeqArtMix/src/SeqArtMix/Entity/Img.php',
  'SeqArtMix\Service\StoreImgService'          => __DIR__ . '/SeqArtMix/src/SeqArtMix/Service/StoreImgService.php',
  'SeqArtMix\Service\ParseImgService'          => __DIR__ . '/SeqArtMix/src/SeqArtMix/Service/ParseImgService.php',
  'SeqArtMix\Mapper\ImgHydrator'               => __DIR__ . '/SeqArtMix/src/SeqArtMix/Mapper/ImgHydrator.php',
  'SeqArtMix\View\Helper\DisplayImgCollection' => __DIR__ . '/SeqArtMix/src/SeqArtMix/View/Helper/DisplayImgCollection.php',
  'SeqArtMix\Controller\IndexController'       => __DIR__ . '/SeqArtMix/src/SeqArtMix/Controller/IndexController.php',
  'SeqArtMix\Controller\AdminController'       => __DIR__ . '/SeqArtMix/src/SeqArtMix/Controller/AdminController.php',
  'SeqArtMix\Form\ImgFieldset'                 => __DIR__ . '/SeqArtMix/src/SeqArtMix/Form/ImgFieldset.php',
  'SeqArtMix\Form\ImgAdd'                      => __DIR__ . '/SeqArtMix/src/SeqArtMix/Form/ImgAdd.php',
);
