<button class="arrow" value="-1" title="-1" id="<?php echo $value->getId() ?>_p">←</button>
    <?php echo $value->getId() ?>
    <span id="<?php echo $value->getId() ?>_d"><?php echo $value->getUrl() ?></span>
<button class="arrow" value="+1" title="+1" id="<?php echo $value->getId() ?>_n">→</button>
<br>
<img src="<?php echo $value->getImgUrl() ?>" alt="<?php echo $value->getId() ?>" id="<?php echo $value->getId() ?>">
<br>

